/*
Aqua Test Suite

0300: Basic throw catch finally

- output
128
256

*/

.class Exception
{
	.field public int32 num

	.method public function .ctor(int32)
	{
		ldfi	$0, Exception::num, $1
		ret
	}
}

.class Test
{
	.method static public function Main()
	{
		.try {
			ldi	$2, 128
			new	$0, Exception::.ctor(int32)
			throw	$0

			/* Should not come here */
			ldi	$0, 12345
			printi	$0
			leave	LABEL
		}
		.catch (Exception $0) {
			ldfi	$0, $0, Exception::num
			printi	$0
			leave	LABEL
		}
		.finally {
			ldi	$0, 256
			printi	$0
			endfinally
		}
LABEL:		ret
	}
}
